export type RecruitmentMember = {
    department: string;
    name: string;
    mobile: string;
    email: string;
    areaOfResidency: string;
    university: string;
    faculty: string;
    graduationYear: string;
    firstPreference: string;
    subFirstPreference?: string;
    subSecondPreference?: string;
    secondPreference: string;
    reasonForApplying: string;
    previousExperience: string;
    q1: string;
    q2: string;
    q3: string;
    q4: string;
};